services:
  postgis:
    volumes:
      - ./postgres-readonly.sh:/postgres-readonly.sh:ro

  backend:
    read_only: true
    volumes:
      - ./work:/data/work/osmose:ro
      - type: tmpfs
        target: /tmp
